In [1]:
!pip install numpy==2.0.2

In [2]:
import numpy as np


In [7]:
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])
#ベクトル演算
print(a + b)
print(a * 2)

In [12]:
#リストのパターン
a_list = [1,2,3,4,5]
b_list = [10,20,30,40,50]
print(a_list + b_list)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


In [14]:
a[1]
a[:3]

array([1, 2, 3])

In [18]:
#統計量計算
a = np.array([1,2,3,4,5])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

15
3.0
3.0
1.4142135623730951


In [19]:
#多次元配列
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
A.shape

(3, 3)

In [21]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [23]:
# numpyを使う例
scores = np.array([[10,20,30],[40,50,60],[70,80,90]])
mean = np.mean(scores)
scores - mean

array([[-40., -30., -20.],
       [-10.,   0.,  10.],
       [ 20.,  30.,  40.]])

In [24]:
mean

np.float64(50.0)

In [25]:
np.random.rand(3,2)

array([[0.08843167, 0.77164963],
       [0.94556887, 0.64673663],
       [0.68142896, 0.89281929]])

In [26]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [30]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])